version: '3.8'

services:

  frontend:
    build:
      context: ./Frontend 
      dockerfile: Dockerfile
      args:
        NGINX_PORT: ${NGINX_PORT}
    ports: 
      - "${NGINX_PORT}:80"
    volumes: 
      - ./Frontend/src:/usr/share/nginx/html  # Hot reload del frontend
      - ./Frontend/nginx.conf:/etc/nginx/nginx.conf:ro  # Configuración de nginx
    container_name: sada-frontend
    env_file: .env


  db:
    image: mysql:8.0
    container_name: sada-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes: 
      - mysql_data:/var/lib/mysql
    ports: 
      - "3307:3306"
    env_file:
     - .env 


volumes:
  mysql_data: