services:

  frontend:
    build:
      context: ./Frontend 
      dockerfile: Dockerfile
      args:
        NGINX_PORT: ${NGINX_PORT}
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./Frontend/src:/usr/share/nginx/html  # Hot reload del frontend
    container_name: sada-frontend
    env_file:
      - .env
    networks:
      - auth_network
    depends_on:
      - backend  

  backend:
    build: 
      context: ./Backend 
      dockerfile: Dockerfile
    container_name: sara-backend
    expose:
      - "3000"
    environment:
      - DB_HOST=db
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
    volumes:
      - ./backend/src:/app/src
      - /app/node_modules
    depends_on:
      - db
    networks:
      - auth_network

  db:
    image: mysql:8.0
    container_name: sara-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    env_file:
      - .env 
    networks:
      - auth_network
    restart:
      unless-stopped

volumes:
  mysql_data:
     name: sara_mysql_data

networks:
  auth_network:
    driver: bridge